README.md, info.md
Signed-off-by: Ludy87 <Ludy87@users.noreply.github.com>
=> 📝 Update Documentation

CHANGELOG.md, custom_components/xplora_watch/__init__.py, custom_components/xplora_watch/binary_sensor.py, custom_components/xplora_watch/device_tracker.py, custom_components/xplora_watch/geocoder.py, custom_components/xplora_watch/manifest.json, custom_components/xplora_watch/notify.py, custom_components/xplora_watch/sensor.py, custom_components/xplora_watch/switch.py
- remove `*_async` (new Lib version)
- remove `await` without async function
- rename `ids` to `watch_ids`
- renmae `id` to `watch_id`
=> 🎨 rename variable - 0.0.29

.github/actions/update_readme.py, CHANGELOG.md, README.md, custom_components/xplora_watch/device_tracker.py, custom_components/xplora_watch/manifest.json
You will be able to find the clock at any time. An inquiry is made every 10 seconds. Note the battery display.
=> 🏗️ resolved #29  tracking device

CHANGELOG.md, custom_components/xplora_watch/__init__.py, custom_components/xplora_watch/binary_sensor.py, custom_components/xplora_watch/device_tracker.py, custom_components/xplora_watch/manifest.json, hacs.json
- 🌱 add error message https://github.com/Ludy87/xplora_watch/issues/24#issuecomment-1203217354 for testing
=> 🌱 add error message V1.0.42

CHANGELOG.md, custom_components/xplora_watch/manifest.json, custom_components/xplora_watch/sensor.py, hacs.json
=> 🐛 Fix Steps sensor (Step counter)  #43

custom_components/xplora_watch/manifest.json, custom_components/xplora_watch/notify.py
Signed-off-by: Ludy87 <Ludy87@users.noreply.github.com>
=> 🐛 Fix error message Notify

custom_components/xplora_watch/device_tracker.py, custom_components/xplora_watch/manifest.json
=> 🌱 add state (not) home Fix #55

custom_components/xplora_watch/__init__.py, custom_components/xplora_watch/coordinator.py, custom_components/xplora_watch/device_tracker.py, custom_components/xplora_watch/manifest.json, hacs.json
Make sure, the state / coordinator always returns a float value
=> Type: Lat and lng - str to float

custom_components/xplora_watch/helper.py
- Added exception handling for writing service definition
- Added correct path-creation using native HA methods
=> IOError: Making helpers more resilient

README.md, custom_components/xplora_watch/__init__.py, custom_components/xplora_watch/binary_sensor.py, custom_components/xplora_watch/config_flow.py, custom_components/xplora_watch/const.py, custom_components/xplora_watch/coordinator.py, custom_components/xplora_watch/device_tracker.py, custom_components/xplora_watch/entity.py, custom_components/xplora_watch/helper.py, custom_components/xplora_watch/manifest.json, custom_components/xplora_watch/sensor.py, custom_components/xplora_watch/services.py, custom_components/xplora_watch/strings.json, custom_components/xplora_watch/switch.py, custom_components/xplora_watch/translations/de.json, custom_components/xplora_watch/translations/en.json, hacs.json
Due to the global spread of the watch, the integration is now multilingual.
HASS Logs will continue to be in English.
=> 📝 add Multilanguage

README.md, custom_components/xplora_watch/const.py, custom_components/xplora_watch/helper.py, custom_components/xplora_watch/manifest.json, custom_components/xplora_watch/services.py
Signed-off-by: Ludy87 <Ludy87@users.noreply.github.com>
=> ✨ Shutdown Watch per Service (v2.5.0)

custom_components/xplora_watch/manifest.json
It should fix the bug listed in Issues #116.
=> 🐛 Fix No module named 'dataclasses_json'

custom_components/xplora_watch/coordinator.py, custom_components/xplora_watch/manifest.json, custom_components/xplora_watch/services.py
Signed-off-by: Ludy87 <Ludy87@users.noreply.github.com>
=> 🐛 Fix update data

custom_components/xplora_watch/manifest.json, custom_components/xplora_watch/switch.py
Fixes unexpected keyword argument 'silentId'
=> 🐛 v2.7.5 fixes #172

custom_components/xplora_watch/coordinator.py, custom_components/xplora_watch/manifest.json
- check the bug for further steps. https://github.com/Ludy87/xplora_watch/issues/174
=> 🐛 v2.7.7-beta

custom_components/xplora_watch/coordinator.py, custom_components/xplora_watch/device_tracker.py, custom_components/xplora_watch/manifest.json, custom_components/xplora_watch/services.py
- check the bug for further steps. sensor and device_tracker states reporting as "unknown" with X5 Play🐛  #174
=> 🐛 v2.7.8-beta

custom_components/xplora_watch/manifest.json
=> v2.13.1 Beta

custom_components/xplora_watch/manifest.json
=> v2.13.2 Beta

custom_components/xplora_watch/__init__.py, custom_components/xplora_watch/binary_sensor.py, custom_components/xplora_watch/config_flow.py, custom_components/xplora_watch/const.py, custom_components/xplora_watch/const_schema.py, custom_components/xplora_watch/coordinator.py, custom_components/xplora_watch/device_tracker.py, custom_components/xplora_watch/entity.py, custom_components/xplora_watch/geocoder.py, custom_components/xplora_watch/helper.py, custom_components/xplora_watch/manifest.json, custom_components/xplora_watch/notify.py, custom_components/xplora_watch/sensor.py, custom_components/xplora_watch/services.py, custom_components/xplora_watch/switch.py
• Added support for the Xplora® Watch Version 2 in various modules, enhancing functionality and user experience.
• Improved code readability and maintenance by adding whitespace in multiple files.
• Enhanced configuration flow for user sign-in, making it more robust and user-friendly.
• Updated the device tracker's logic for tracking and displaying watch location and status, offering more accurate and detailed information.
• Updated the pyxplora_api library version from 2.12.3 to 2.12.4, ensuring better compatibility and performance.
• Upgraded the integration version to v2.13.3.beta, reflecting the latest changes and improvements.
=> v2.13.3 Beta

custom_components/xplora_watch/manifest.json
• Updated the pyxplora_api library version from 2.12.4 to 2.12.5, ensuring ongoing compatibility and enhanced performance.
• The integration version has been upgraded to v2.13.4-beta, reflecting the latest advancements and fine-tunings.
=> v2.13.4 Beta

custom_components/xplora_watch/config_flow.py, custom_components/xplora_watch/const.py, custom_components/xplora_watch/const_schema.py, custom_components/xplora_watch/coordinator.py, custom_components/xplora_watch/manifest.json, hacs.json
• Streamlined the CONF_COUNTRY_CODE by removing its redundancy across multiple modules, resulting in cleaner and more efficient code.
• Upgraded the pyxplora_api library from version 2.12.5 to 2.12.6, ensuring the integration stays up-to-date with the latest API changes.
• Updated aiohttp library to version 3.9.3, enhancing the overall stability and performance of the integration.
• Advanced the integration version to v2.13.5, reflecting these latest improvements.
• Updated compatibility with Home Assistant to version 2024.1.6, ensuring seamless integration with the latest Home Assistant release.
• Upgraded HACS compatibility to version 1.34.0, offering a smoother experience within the Home Assistant Community Store.
=> 🐛 compatibility update

custom_components/xplora_watch/coordinator.py, custom_components/xplora_watch/manifest.json, custom_components/xplora_watch/services.py, hacs.json
• Improved type hinting in coordinator.py by explicitly defining self._entry as ConfigEntry. This enhances code readability and maintainability.
• Advanced the integration version to v2.13.6, reflecting the ongoing commitment to continuous improvement.
• Updated the compatibility with Home Assistant to version 2024.2.0, ensuring a seamless experience with the latest Home Assistant release.
• Optimized the async_see function in services.py by utilizing the .get method for better efficiency.
• Refactored voice, video, and thumbnail fetching logic in services.py for improved clarity and performance.
=> 🐛 wrong type definition

custom_components/xplora_watch/manifest.json, hacs.json
=> Bump aiohttp, pyxplora_api

custom_components/xplora_watch/manifest.json, hacs.json
=> Bump pyxplora_api from 2.12.8 to 2.12.9

custom_components/xplora_watch/helper.py, custom_components/xplora_watch/manifest.json, hacs.json
=> Fix: Detected blocking call to open inside the event loop
